// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command/command.proto

package com.fepoc.ac.acn.cmd;

public interface CommandReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:command.CommandReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.command.CommandReply.ErrorMap errorMap = 1;</code>
   * @return Whether the errorMap field is set.
   */
  boolean hasErrorMap();
  /**
   * <code>.command.CommandReply.ErrorMap errorMap = 1;</code>
   * @return The errorMap.
   */
  com.fepoc.ac.acn.cmd.CommandReply.ErrorMap getErrorMap();
  /**
   * <code>.command.CommandReply.ErrorMap errorMap = 1;</code>
   */
  com.fepoc.ac.acn.cmd.CommandReply.ErrorMapOrBuilder getErrorMapOrBuilder();

  /**
   * <code>.command.CommandReply.State state = 2;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>.command.CommandReply.State state = 2;</code>
   * @return The state.
   */
  com.fepoc.ac.acn.cmd.CommandReply.State getState();
  /**
   * <code>.command.CommandReply.State state = 2;</code>
   */
  com.fepoc.ac.acn.cmd.CommandReply.StateOrBuilder getStateOrBuilder();

  public com.fepoc.ac.acn.cmd.CommandReply.ResponseCase getResponseCase();
}
