// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command/command.proto

package com.fepoc.ac.acn.cmd;

/**
 * <pre>
 * The request message
 * </pre>
 *
 * Protobuf type {@code command.CommandRequest}
 */
public  final class CommandRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:command.CommandRequest)
    CommandRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommandRequest.newBuilder() to construct.
  private CommandRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommandRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CommandRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommandRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.fepoc.ac.acn.cmd.CommandHeader.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(com.fepoc.ac.acn.cmd.CommandHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.fepoc.ac.acn.cmd.CommandBody.Builder subBuilder = null;
            if (body_ != null) {
              subBuilder = body_.toBuilder();
            }
            body_ = input.readMessage(com.fepoc.ac.acn.cmd.CommandBody.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(body_);
              body_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fepoc.ac.acn.cmd.CommandRequest.class, com.fepoc.ac.acn.cmd.CommandRequest.Builder.class);
  }

  public static final int HEADER_FIELD_NUMBER = 1;
  private com.fepoc.ac.acn.cmd.CommandHeader header_;
  /**
   * <code>.command.CommandHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <code>.command.CommandHeader header = 1;</code>
   * @return The header.
   */
  public com.fepoc.ac.acn.cmd.CommandHeader getHeader() {
    return header_ == null ? com.fepoc.ac.acn.cmd.CommandHeader.getDefaultInstance() : header_;
  }
  /**
   * <code>.command.CommandHeader header = 1;</code>
   */
  public com.fepoc.ac.acn.cmd.CommandHeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int BODY_FIELD_NUMBER = 2;
  private com.fepoc.ac.acn.cmd.CommandBody body_;
  /**
   * <code>.command.CommandBody body = 2;</code>
   * @return Whether the body field is set.
   */
  public boolean hasBody() {
    return body_ != null;
  }
  /**
   * <code>.command.CommandBody body = 2;</code>
   * @return The body.
   */
  public com.fepoc.ac.acn.cmd.CommandBody getBody() {
    return body_ == null ? com.fepoc.ac.acn.cmd.CommandBody.getDefaultInstance() : body_;
  }
  /**
   * <code>.command.CommandBody body = 2;</code>
   */
  public com.fepoc.ac.acn.cmd.CommandBodyOrBuilder getBodyOrBuilder() {
    return getBody();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (body_ != null) {
      output.writeMessage(2, getBody());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (body_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBody());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fepoc.ac.acn.cmd.CommandRequest)) {
      return super.equals(obj);
    }
    com.fepoc.ac.acn.cmd.CommandRequest other = (com.fepoc.ac.acn.cmd.CommandRequest) obj;

    if (hasHeader() != other.hasHeader()) return false;
    if (hasHeader()) {
      if (!getHeader()
          .equals(other.getHeader())) return false;
    }
    if (hasBody() != other.hasBody()) return false;
    if (hasBody()) {
      if (!getBody()
          .equals(other.getBody())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    if (hasBody()) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fepoc.ac.acn.cmd.CommandRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fepoc.ac.acn.cmd.CommandRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fepoc.ac.acn.cmd.CommandRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fepoc.ac.acn.cmd.CommandRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fepoc.ac.acn.cmd.CommandRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fepoc.ac.acn.cmd.CommandRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fepoc.ac.acn.cmd.CommandRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fepoc.ac.acn.cmd.CommandRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fepoc.ac.acn.cmd.CommandRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fepoc.ac.acn.cmd.CommandRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fepoc.ac.acn.cmd.CommandRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fepoc.ac.acn.cmd.CommandRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fepoc.ac.acn.cmd.CommandRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message
   * </pre>
   *
   * Protobuf type {@code command.CommandRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:command.CommandRequest)
      com.fepoc.ac.acn.cmd.CommandRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fepoc.ac.acn.cmd.CommandRequest.class, com.fepoc.ac.acn.cmd.CommandRequest.Builder.class);
    }

    // Construct using com.fepoc.ac.acn.cmd.CommandRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      if (bodyBuilder_ == null) {
        body_ = null;
      } else {
        body_ = null;
        bodyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandRequest_descriptor;
    }

    @java.lang.Override
    public com.fepoc.ac.acn.cmd.CommandRequest getDefaultInstanceForType() {
      return com.fepoc.ac.acn.cmd.CommandRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.fepoc.ac.acn.cmd.CommandRequest build() {
      com.fepoc.ac.acn.cmd.CommandRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fepoc.ac.acn.cmd.CommandRequest buildPartial() {
      com.fepoc.ac.acn.cmd.CommandRequest result = new com.fepoc.ac.acn.cmd.CommandRequest(this);
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      if (bodyBuilder_ == null) {
        result.body_ = body_;
      } else {
        result.body_ = bodyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fepoc.ac.acn.cmd.CommandRequest) {
        return mergeFrom((com.fepoc.ac.acn.cmd.CommandRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fepoc.ac.acn.cmd.CommandRequest other) {
      if (other == com.fepoc.ac.acn.cmd.CommandRequest.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (other.hasBody()) {
        mergeBody(other.getBody());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fepoc.ac.acn.cmd.CommandRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fepoc.ac.acn.cmd.CommandRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.fepoc.ac.acn.cmd.CommandHeader header_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fepoc.ac.acn.cmd.CommandHeader, com.fepoc.ac.acn.cmd.CommandHeader.Builder, com.fepoc.ac.acn.cmd.CommandHeaderOrBuilder> headerBuilder_;
    /**
     * <code>.command.CommandHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }
    /**
     * <code>.command.CommandHeader header = 1;</code>
     * @return The header.
     */
    public com.fepoc.ac.acn.cmd.CommandHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? com.fepoc.ac.acn.cmd.CommandHeader.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <code>.command.CommandHeader header = 1;</code>
     */
    public Builder setHeader(com.fepoc.ac.acn.cmd.CommandHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.command.CommandHeader header = 1;</code>
     */
    public Builder setHeader(
        com.fepoc.ac.acn.cmd.CommandHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.command.CommandHeader header = 1;</code>
     */
    public Builder mergeHeader(com.fepoc.ac.acn.cmd.CommandHeader value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            com.fepoc.ac.acn.cmd.CommandHeader.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.command.CommandHeader header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.command.CommandHeader header = 1;</code>
     */
    public com.fepoc.ac.acn.cmd.CommandHeader.Builder getHeaderBuilder() {
      
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.command.CommandHeader header = 1;</code>
     */
    public com.fepoc.ac.acn.cmd.CommandHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            com.fepoc.ac.acn.cmd.CommandHeader.getDefaultInstance() : header_;
      }
    }
    /**
     * <code>.command.CommandHeader header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fepoc.ac.acn.cmd.CommandHeader, com.fepoc.ac.acn.cmd.CommandHeader.Builder, com.fepoc.ac.acn.cmd.CommandHeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fepoc.ac.acn.cmd.CommandHeader, com.fepoc.ac.acn.cmd.CommandHeader.Builder, com.fepoc.ac.acn.cmd.CommandHeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private com.fepoc.ac.acn.cmd.CommandBody body_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fepoc.ac.acn.cmd.CommandBody, com.fepoc.ac.acn.cmd.CommandBody.Builder, com.fepoc.ac.acn.cmd.CommandBodyOrBuilder> bodyBuilder_;
    /**
     * <code>.command.CommandBody body = 2;</code>
     * @return Whether the body field is set.
     */
    public boolean hasBody() {
      return bodyBuilder_ != null || body_ != null;
    }
    /**
     * <code>.command.CommandBody body = 2;</code>
     * @return The body.
     */
    public com.fepoc.ac.acn.cmd.CommandBody getBody() {
      if (bodyBuilder_ == null) {
        return body_ == null ? com.fepoc.ac.acn.cmd.CommandBody.getDefaultInstance() : body_;
      } else {
        return bodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.command.CommandBody body = 2;</code>
     */
    public Builder setBody(com.fepoc.ac.acn.cmd.CommandBody value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        bodyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.command.CommandBody body = 2;</code>
     */
    public Builder setBody(
        com.fepoc.ac.acn.cmd.CommandBody.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        bodyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.command.CommandBody body = 2;</code>
     */
    public Builder mergeBody(com.fepoc.ac.acn.cmd.CommandBody value) {
      if (bodyBuilder_ == null) {
        if (body_ != null) {
          body_ =
            com.fepoc.ac.acn.cmd.CommandBody.newBuilder(body_).mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        bodyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.command.CommandBody body = 2;</code>
     */
    public Builder clearBody() {
      if (bodyBuilder_ == null) {
        body_ = null;
        onChanged();
      } else {
        body_ = null;
        bodyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.command.CommandBody body = 2;</code>
     */
    public com.fepoc.ac.acn.cmd.CommandBody.Builder getBodyBuilder() {
      
      onChanged();
      return getBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.command.CommandBody body = 2;</code>
     */
    public com.fepoc.ac.acn.cmd.CommandBodyOrBuilder getBodyOrBuilder() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilder();
      } else {
        return body_ == null ?
            com.fepoc.ac.acn.cmd.CommandBody.getDefaultInstance() : body_;
      }
    }
    /**
     * <code>.command.CommandBody body = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fepoc.ac.acn.cmd.CommandBody, com.fepoc.ac.acn.cmd.CommandBody.Builder, com.fepoc.ac.acn.cmd.CommandBodyOrBuilder> 
        getBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fepoc.ac.acn.cmd.CommandBody, com.fepoc.ac.acn.cmd.CommandBody.Builder, com.fepoc.ac.acn.cmd.CommandBodyOrBuilder>(
                getBody(),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:command.CommandRequest)
  }

  // @@protoc_insertion_point(class_scope:command.CommandRequest)
  private static final com.fepoc.ac.acn.cmd.CommandRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fepoc.ac.acn.cmd.CommandRequest();
  }

  public static com.fepoc.ac.acn.cmd.CommandRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommandRequest>
      PARSER = new com.google.protobuf.AbstractParser<CommandRequest>() {
    @java.lang.Override
    public CommandRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommandRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommandRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommandRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fepoc.ac.acn.cmd.CommandRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

