// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command/command.proto

package com.fepoc.ac.acn.cmd;

public final class CommandProto {
  private CommandProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandHeader_Login_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandHeader_Login_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandBody_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandBody_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandBody_ParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandBody_ParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandReply_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandReply_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandReply_ErrorMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandReply_ErrorMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandReply_ErrorMap_ErrorEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandReply_ErrorMap_ErrorEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_command_CommandReply_State_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_command_CommandReply_State_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025command/command.proto\022\007command\032\031google" +
      "/protobuf/any.proto\"\\\n\016CommandRequest\022&\n" +
      "\006header\030\001 \001(\0132\026.command.CommandHeader\022\"\n" +
      "\004body\030\002 \001(\0132\024.command.CommandBody\"\242\001\n\rCo" +
      "mmandHeader\022-\n\005login\030\001 \001(\0132\034.command.Com" +
      "mandHeader.LoginH\000\022\025\n\013accessToken\030\002 \001(\014H" +
      "\000\022\023\n\013application\030\003 \001(\t\032)\n\005Login\022\016\n\006clien" +
      "t\030\001 \001(\t\022\020\n\010password\030\002 \001(\014B\013\n\tAuthorize\"\275" +
      "\002\n\013CommandBody\022\021\n\tcommandNo\030\001 \001(\005\022,\n\004tag" +
      "s\030\002 \003(\0132\036.command.CommandBody.TagsEntry\022" +
      "0\n\006params\030\003 \003(\0132 .command.CommandBody.Pa" +
      "ramsEntry\022\"\n\004keys\030\004 \001(\0132\024.google.protobu" +
      "f.Any\022%\n\007payload\030\005 \001(\0132\024.google.protobuf" +
      ".Any\032+\n\tTagsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001\032C\n\013ParamsEntry\022\013\n\003key\030\001 \001(\t\022#\n" +
      "\005value\030\002 \001(\0132\024.google.protobuf.Any:\0028\001\"\221" +
      "\003\n\014CommandReply\0222\n\010errorMap\030\001 \001(\0132\036.comm" +
      "and.CommandReply.ErrorMapH\000\022,\n\005state\030\002 \001" +
      "(\0132\033.command.CommandReply.StateH\000\032,\n\005Err" +
      "or\022\021\n\terrorCode\030\001 \001(\t\022\020\n\010errorMsg\030\002 \001(\t\032" +
      "\217\001\n\010ErrorMap\0228\n\005error\030\001 \003(\0132).command.Co" +
      "mmandReply.ErrorMap.ErrorEntry\032I\n\nErrorE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022*\n\005value\030\002 \001(\0132\033.comma" +
      "nd.CommandReply.Error:\0028\001\032S\n\005State\022\021\n\tst" +
      "ateCode\030\001 \001(\t\022\020\n\010stateMsg\030\002 \001(\t\022%\n\007paylo" +
      "ad\030\003 \001(\0132\024.google.protobuf.AnyB\n\n\010Respon" +
      "se2\366\001\n\007Commlet\022;\n\007connect\022\027.command.Comm" +
      "andRequest\032\025.command.CommandReply\"\000\0227\n\003g" +
      "et\022\027.command.CommandRequest\032\025.command.Co" +
      "mmandReply\"\000\0227\n\003put\022\027.command.CommandReq" +
      "uest\032\025.command.CommandReply\"\000\022<\n\010validat" +
      "e\022\027.command.CommandRequest\032\025.command.Com" +
      "mandReply\"\000B,\n\024com.fepoc.ac.acn.cmdB\014Com" +
      "mandProtoP\001\242\002\003CMDb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_command_CommandRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_command_CommandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandRequest_descriptor,
        new java.lang.String[] { "Header", "Body", });
    internal_static_command_CommandHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_command_CommandHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandHeader_descriptor,
        new java.lang.String[] { "Login", "AccessToken", "Application", "Authorize", });
    internal_static_command_CommandHeader_Login_descriptor =
      internal_static_command_CommandHeader_descriptor.getNestedTypes().get(0);
    internal_static_command_CommandHeader_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandHeader_Login_descriptor,
        new java.lang.String[] { "Client", "Password", });
    internal_static_command_CommandBody_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_command_CommandBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandBody_descriptor,
        new java.lang.String[] { "CommandNo", "Tags", "Params", "Keys", "Payload", });
    internal_static_command_CommandBody_TagsEntry_descriptor =
      internal_static_command_CommandBody_descriptor.getNestedTypes().get(0);
    internal_static_command_CommandBody_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandBody_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_command_CommandBody_ParamsEntry_descriptor =
      internal_static_command_CommandBody_descriptor.getNestedTypes().get(1);
    internal_static_command_CommandBody_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandBody_ParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_command_CommandReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_command_CommandReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandReply_descriptor,
        new java.lang.String[] { "ErrorMap", "State", "Response", });
    internal_static_command_CommandReply_Error_descriptor =
      internal_static_command_CommandReply_descriptor.getNestedTypes().get(0);
    internal_static_command_CommandReply_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandReply_Error_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMsg", });
    internal_static_command_CommandReply_ErrorMap_descriptor =
      internal_static_command_CommandReply_descriptor.getNestedTypes().get(1);
    internal_static_command_CommandReply_ErrorMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandReply_ErrorMap_descriptor,
        new java.lang.String[] { "Error", });
    internal_static_command_CommandReply_ErrorMap_ErrorEntry_descriptor =
      internal_static_command_CommandReply_ErrorMap_descriptor.getNestedTypes().get(0);
    internal_static_command_CommandReply_ErrorMap_ErrorEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandReply_ErrorMap_ErrorEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_command_CommandReply_State_descriptor =
      internal_static_command_CommandReply_descriptor.getNestedTypes().get(2);
    internal_static_command_CommandReply_State_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_command_CommandReply_State_descriptor,
        new java.lang.String[] { "StateCode", "StateMsg", "Payload", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
