// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command/command.proto

package com.fepoc.ac.acn.cmd;

public interface CommandBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:command.CommandBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 commandNo = 1;</code>
   * @return The commandNo.
   */
  int getCommandNo();

  /**
   * <code>map&lt;string, string&gt; tags = 2;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 2;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 2;</code>
   */

  java.lang.String getTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 2;</code>
   */

  java.lang.String getTagsOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; params = 3;</code>
   */
  int getParamsCount();
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; params = 3;</code>
   */
  boolean containsParams(
      java.lang.String key);
  /**
   * Use {@link #getParamsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.Any>
  getParams();
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; params = 3;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.Any>
  getParamsMap();
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; params = 3;</code>
   */

  com.google.protobuf.Any getParamsOrDefault(
      java.lang.String key,
      com.google.protobuf.Any defaultValue);
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; params = 3;</code>
   */

  com.google.protobuf.Any getParamsOrThrow(
      java.lang.String key);

  /**
   * <code>.google.protobuf.Any keys = 4;</code>
   * @return Whether the keys field is set.
   */
  boolean hasKeys();
  /**
   * <code>.google.protobuf.Any keys = 4;</code>
   * @return The keys.
   */
  com.google.protobuf.Any getKeys();
  /**
   * <code>.google.protobuf.Any keys = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getKeysOrBuilder();

  /**
   * <code>.google.protobuf.Any payload = 5;</code>
   * @return Whether the payload field is set.
   */
  boolean hasPayload();
  /**
   * <code>.google.protobuf.Any payload = 5;</code>
   * @return The payload.
   */
  com.google.protobuf.Any getPayload();
  /**
   * <code>.google.protobuf.Any payload = 5;</code>
   */
  com.google.protobuf.AnyOrBuilder getPayloadOrBuilder();
}
