// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command/command.proto

package com.fepoc.ac.acn.cmd;

/**
 * Protobuf type {@code command.CommandHeader}
 */
public  final class CommandHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:command.CommandHeader)
    CommandHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommandHeader.newBuilder() to construct.
  private CommandHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommandHeader() {
    application_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CommandHeader();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommandHeader(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.fepoc.ac.acn.cmd.CommandHeader.Login.Builder subBuilder = null;
            if (authorizeCase_ == 1) {
              subBuilder = ((com.fepoc.ac.acn.cmd.CommandHeader.Login) authorize_).toBuilder();
            }
            authorize_ =
                input.readMessage(com.fepoc.ac.acn.cmd.CommandHeader.Login.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.fepoc.ac.acn.cmd.CommandHeader.Login) authorize_);
              authorize_ = subBuilder.buildPartial();
            }
            authorizeCase_ = 1;
            break;
          }
          case 18: {
            authorizeCase_ = 2;
            authorize_ = input.readBytes();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            application_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandHeader_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fepoc.ac.acn.cmd.CommandHeader.class, com.fepoc.ac.acn.cmd.CommandHeader.Builder.class);
  }

  public interface LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:command.CommandHeader.Login)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string client = 1;</code>
     * @return The client.
     */
    java.lang.String getClient();
    /**
     * <code>string client = 1;</code>
     * @return The bytes for client.
     */
    com.google.protobuf.ByteString
        getClientBytes();

    /**
     * <code>bytes password = 2;</code>
     * @return The password.
     */
    com.google.protobuf.ByteString getPassword();
  }
  /**
   * Protobuf type {@code command.CommandHeader.Login}
   */
  public  static final class Login extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:command.CommandHeader.Login)
      LoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Login() {
      client_ = "";
      password_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Login();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              client_ = s;
              break;
            }
            case 18: {

              password_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandHeader_Login_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandHeader_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fepoc.ac.acn.cmd.CommandHeader.Login.class, com.fepoc.ac.acn.cmd.CommandHeader.Login.Builder.class);
    }

    public static final int CLIENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object client_;
    /**
     * <code>string client = 1;</code>
     * @return The client.
     */
    public java.lang.String getClient() {
      java.lang.Object ref = client_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        client_ = s;
        return s;
      }
    }
    /**
     * <code>string client = 1;</code>
     * @return The bytes for client.
     */
    public com.google.protobuf.ByteString
        getClientBytes() {
      java.lang.Object ref = client_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        client_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString password_;
    /**
     * <code>bytes password = 2;</code>
     * @return The password.
     */
    public com.google.protobuf.ByteString getPassword() {
      return password_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, client_);
      }
      if (!password_.isEmpty()) {
        output.writeBytes(2, password_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, client_);
      }
      if (!password_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fepoc.ac.acn.cmd.CommandHeader.Login)) {
        return super.equals(obj);
      }
      com.fepoc.ac.acn.cmd.CommandHeader.Login other = (com.fepoc.ac.acn.cmd.CommandHeader.Login) obj;

      if (!getClient()
          .equals(other.getClient())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClient().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fepoc.ac.acn.cmd.CommandHeader.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fepoc.ac.acn.cmd.CommandHeader.Login prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code command.CommandHeader.Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:command.CommandHeader.Login)
        com.fepoc.ac.acn.cmd.CommandHeader.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandHeader_Login_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandHeader_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fepoc.ac.acn.cmd.CommandHeader.Login.class, com.fepoc.ac.acn.cmd.CommandHeader.Login.Builder.class);
      }

      // Construct using com.fepoc.ac.acn.cmd.CommandHeader.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        client_ = "";

        password_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandHeader_Login_descriptor;
      }

      @java.lang.Override
      public com.fepoc.ac.acn.cmd.CommandHeader.Login getDefaultInstanceForType() {
        return com.fepoc.ac.acn.cmd.CommandHeader.Login.getDefaultInstance();
      }

      @java.lang.Override
      public com.fepoc.ac.acn.cmd.CommandHeader.Login build() {
        com.fepoc.ac.acn.cmd.CommandHeader.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fepoc.ac.acn.cmd.CommandHeader.Login buildPartial() {
        com.fepoc.ac.acn.cmd.CommandHeader.Login result = new com.fepoc.ac.acn.cmd.CommandHeader.Login(this);
        result.client_ = client_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fepoc.ac.acn.cmd.CommandHeader.Login) {
          return mergeFrom((com.fepoc.ac.acn.cmd.CommandHeader.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fepoc.ac.acn.cmd.CommandHeader.Login other) {
        if (other == com.fepoc.ac.acn.cmd.CommandHeader.Login.getDefaultInstance()) return this;
        if (!other.getClient().isEmpty()) {
          client_ = other.client_;
          onChanged();
        }
        if (other.getPassword() != com.google.protobuf.ByteString.EMPTY) {
          setPassword(other.getPassword());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fepoc.ac.acn.cmd.CommandHeader.Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fepoc.ac.acn.cmd.CommandHeader.Login) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object client_ = "";
      /**
       * <code>string client = 1;</code>
       * @return The client.
       */
      public java.lang.String getClient() {
        java.lang.Object ref = client_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          client_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client = 1;</code>
       * @return The bytes for client.
       */
      public com.google.protobuf.ByteString
          getClientBytes() {
        java.lang.Object ref = client_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          client_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client = 1;</code>
       * @param value The client to set.
       * @return This builder for chaining.
       */
      public Builder setClient(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        client_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClient() {
        
        client_ = getDefaultInstance().getClient();
        onChanged();
        return this;
      }
      /**
       * <code>string client = 1;</code>
       * @param value The bytes for client to set.
       * @return This builder for chaining.
       */
      public Builder setClientBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        client_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString password_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes password = 2;</code>
       * @return The password.
       */
      public com.google.protobuf.ByteString getPassword() {
        return password_;
      }
      /**
       * <code>bytes password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:command.CommandHeader.Login)
    }

    // @@protoc_insertion_point(class_scope:command.CommandHeader.Login)
    private static final com.fepoc.ac.acn.cmd.CommandHeader.Login DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fepoc.ac.acn.cmd.CommandHeader.Login();
    }

    public static com.fepoc.ac.acn.cmd.CommandHeader.Login getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Login>
        PARSER = new com.google.protobuf.AbstractParser<Login>() {
      @java.lang.Override
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Login(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Login> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fepoc.ac.acn.cmd.CommandHeader.Login getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int authorizeCase_ = 0;
  private java.lang.Object authorize_;
  public enum AuthorizeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LOGIN(1),
    ACCESSTOKEN(2),
    AUTHORIZE_NOT_SET(0);
    private final int value;
    private AuthorizeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AuthorizeCase valueOf(int value) {
      return forNumber(value);
    }

    public static AuthorizeCase forNumber(int value) {
      switch (value) {
        case 1: return LOGIN;
        case 2: return ACCESSTOKEN;
        case 0: return AUTHORIZE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public AuthorizeCase
  getAuthorizeCase() {
    return AuthorizeCase.forNumber(
        authorizeCase_);
  }

  public static final int LOGIN_FIELD_NUMBER = 1;
  /**
   * <code>.command.CommandHeader.Login login = 1;</code>
   * @return Whether the login field is set.
   */
  public boolean hasLogin() {
    return authorizeCase_ == 1;
  }
  /**
   * <code>.command.CommandHeader.Login login = 1;</code>
   * @return The login.
   */
  public com.fepoc.ac.acn.cmd.CommandHeader.Login getLogin() {
    if (authorizeCase_ == 1) {
       return (com.fepoc.ac.acn.cmd.CommandHeader.Login) authorize_;
    }
    return com.fepoc.ac.acn.cmd.CommandHeader.Login.getDefaultInstance();
  }
  /**
   * <code>.command.CommandHeader.Login login = 1;</code>
   */
  public com.fepoc.ac.acn.cmd.CommandHeader.LoginOrBuilder getLoginOrBuilder() {
    if (authorizeCase_ == 1) {
       return (com.fepoc.ac.acn.cmd.CommandHeader.Login) authorize_;
    }
    return com.fepoc.ac.acn.cmd.CommandHeader.Login.getDefaultInstance();
  }

  public static final int ACCESSTOKEN_FIELD_NUMBER = 2;
  /**
   * <code>bytes accessToken = 2;</code>
   * @return The accessToken.
   */
  public com.google.protobuf.ByteString getAccessToken() {
    if (authorizeCase_ == 2) {
      return (com.google.protobuf.ByteString) authorize_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int APPLICATION_FIELD_NUMBER = 3;
  private volatile java.lang.Object application_;
  /**
   * <code>string application = 3;</code>
   * @return The application.
   */
  public java.lang.String getApplication() {
    java.lang.Object ref = application_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      application_ = s;
      return s;
    }
  }
  /**
   * <code>string application = 3;</code>
   * @return The bytes for application.
   */
  public com.google.protobuf.ByteString
      getApplicationBytes() {
    java.lang.Object ref = application_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      application_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (authorizeCase_ == 1) {
      output.writeMessage(1, (com.fepoc.ac.acn.cmd.CommandHeader.Login) authorize_);
    }
    if (authorizeCase_ == 2) {
      output.writeBytes(
          2, (com.google.protobuf.ByteString) authorize_);
    }
    if (!getApplicationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, application_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (authorizeCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.fepoc.ac.acn.cmd.CommandHeader.Login) authorize_);
    }
    if (authorizeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            2, (com.google.protobuf.ByteString) authorize_);
    }
    if (!getApplicationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, application_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fepoc.ac.acn.cmd.CommandHeader)) {
      return super.equals(obj);
    }
    com.fepoc.ac.acn.cmd.CommandHeader other = (com.fepoc.ac.acn.cmd.CommandHeader) obj;

    if (!getApplication()
        .equals(other.getApplication())) return false;
    if (!getAuthorizeCase().equals(other.getAuthorizeCase())) return false;
    switch (authorizeCase_) {
      case 1:
        if (!getLogin()
            .equals(other.getLogin())) return false;
        break;
      case 2:
        if (!getAccessToken()
            .equals(other.getAccessToken())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APPLICATION_FIELD_NUMBER;
    hash = (53 * hash) + getApplication().hashCode();
    switch (authorizeCase_) {
      case 1:
        hash = (37 * hash) + LOGIN_FIELD_NUMBER;
        hash = (53 * hash) + getLogin().hashCode();
        break;
      case 2:
        hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getAccessToken().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fepoc.ac.acn.cmd.CommandHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fepoc.ac.acn.cmd.CommandHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fepoc.ac.acn.cmd.CommandHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fepoc.ac.acn.cmd.CommandHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fepoc.ac.acn.cmd.CommandHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fepoc.ac.acn.cmd.CommandHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fepoc.ac.acn.cmd.CommandHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fepoc.ac.acn.cmd.CommandHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fepoc.ac.acn.cmd.CommandHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fepoc.ac.acn.cmd.CommandHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fepoc.ac.acn.cmd.CommandHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fepoc.ac.acn.cmd.CommandHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fepoc.ac.acn.cmd.CommandHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code command.CommandHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:command.CommandHeader)
      com.fepoc.ac.acn.cmd.CommandHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fepoc.ac.acn.cmd.CommandHeader.class, com.fepoc.ac.acn.cmd.CommandHeader.Builder.class);
    }

    // Construct using com.fepoc.ac.acn.cmd.CommandHeader.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      application_ = "";

      authorizeCase_ = 0;
      authorize_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fepoc.ac.acn.cmd.CommandProto.internal_static_command_CommandHeader_descriptor;
    }

    @java.lang.Override
    public com.fepoc.ac.acn.cmd.CommandHeader getDefaultInstanceForType() {
      return com.fepoc.ac.acn.cmd.CommandHeader.getDefaultInstance();
    }

    @java.lang.Override
    public com.fepoc.ac.acn.cmd.CommandHeader build() {
      com.fepoc.ac.acn.cmd.CommandHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fepoc.ac.acn.cmd.CommandHeader buildPartial() {
      com.fepoc.ac.acn.cmd.CommandHeader result = new com.fepoc.ac.acn.cmd.CommandHeader(this);
      if (authorizeCase_ == 1) {
        if (loginBuilder_ == null) {
          result.authorize_ = authorize_;
        } else {
          result.authorize_ = loginBuilder_.build();
        }
      }
      if (authorizeCase_ == 2) {
        result.authorize_ = authorize_;
      }
      result.application_ = application_;
      result.authorizeCase_ = authorizeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fepoc.ac.acn.cmd.CommandHeader) {
        return mergeFrom((com.fepoc.ac.acn.cmd.CommandHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fepoc.ac.acn.cmd.CommandHeader other) {
      if (other == com.fepoc.ac.acn.cmd.CommandHeader.getDefaultInstance()) return this;
      if (!other.getApplication().isEmpty()) {
        application_ = other.application_;
        onChanged();
      }
      switch (other.getAuthorizeCase()) {
        case LOGIN: {
          mergeLogin(other.getLogin());
          break;
        }
        case ACCESSTOKEN: {
          setAccessToken(other.getAccessToken());
          break;
        }
        case AUTHORIZE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fepoc.ac.acn.cmd.CommandHeader parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fepoc.ac.acn.cmd.CommandHeader) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int authorizeCase_ = 0;
    private java.lang.Object authorize_;
    public AuthorizeCase
        getAuthorizeCase() {
      return AuthorizeCase.forNumber(
          authorizeCase_);
    }

    public Builder clearAuthorize() {
      authorizeCase_ = 0;
      authorize_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.fepoc.ac.acn.cmd.CommandHeader.Login, com.fepoc.ac.acn.cmd.CommandHeader.Login.Builder, com.fepoc.ac.acn.cmd.CommandHeader.LoginOrBuilder> loginBuilder_;
    /**
     * <code>.command.CommandHeader.Login login = 1;</code>
     * @return Whether the login field is set.
     */
    public boolean hasLogin() {
      return authorizeCase_ == 1;
    }
    /**
     * <code>.command.CommandHeader.Login login = 1;</code>
     * @return The login.
     */
    public com.fepoc.ac.acn.cmd.CommandHeader.Login getLogin() {
      if (loginBuilder_ == null) {
        if (authorizeCase_ == 1) {
          return (com.fepoc.ac.acn.cmd.CommandHeader.Login) authorize_;
        }
        return com.fepoc.ac.acn.cmd.CommandHeader.Login.getDefaultInstance();
      } else {
        if (authorizeCase_ == 1) {
          return loginBuilder_.getMessage();
        }
        return com.fepoc.ac.acn.cmd.CommandHeader.Login.getDefaultInstance();
      }
    }
    /**
     * <code>.command.CommandHeader.Login login = 1;</code>
     */
    public Builder setLogin(com.fepoc.ac.acn.cmd.CommandHeader.Login value) {
      if (loginBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        authorize_ = value;
        onChanged();
      } else {
        loginBuilder_.setMessage(value);
      }
      authorizeCase_ = 1;
      return this;
    }
    /**
     * <code>.command.CommandHeader.Login login = 1;</code>
     */
    public Builder setLogin(
        com.fepoc.ac.acn.cmd.CommandHeader.Login.Builder builderForValue) {
      if (loginBuilder_ == null) {
        authorize_ = builderForValue.build();
        onChanged();
      } else {
        loginBuilder_.setMessage(builderForValue.build());
      }
      authorizeCase_ = 1;
      return this;
    }
    /**
     * <code>.command.CommandHeader.Login login = 1;</code>
     */
    public Builder mergeLogin(com.fepoc.ac.acn.cmd.CommandHeader.Login value) {
      if (loginBuilder_ == null) {
        if (authorizeCase_ == 1 &&
            authorize_ != com.fepoc.ac.acn.cmd.CommandHeader.Login.getDefaultInstance()) {
          authorize_ = com.fepoc.ac.acn.cmd.CommandHeader.Login.newBuilder((com.fepoc.ac.acn.cmd.CommandHeader.Login) authorize_)
              .mergeFrom(value).buildPartial();
        } else {
          authorize_ = value;
        }
        onChanged();
      } else {
        if (authorizeCase_ == 1) {
          loginBuilder_.mergeFrom(value);
        }
        loginBuilder_.setMessage(value);
      }
      authorizeCase_ = 1;
      return this;
    }
    /**
     * <code>.command.CommandHeader.Login login = 1;</code>
     */
    public Builder clearLogin() {
      if (loginBuilder_ == null) {
        if (authorizeCase_ == 1) {
          authorizeCase_ = 0;
          authorize_ = null;
          onChanged();
        }
      } else {
        if (authorizeCase_ == 1) {
          authorizeCase_ = 0;
          authorize_ = null;
        }
        loginBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.command.CommandHeader.Login login = 1;</code>
     */
    public com.fepoc.ac.acn.cmd.CommandHeader.Login.Builder getLoginBuilder() {
      return getLoginFieldBuilder().getBuilder();
    }
    /**
     * <code>.command.CommandHeader.Login login = 1;</code>
     */
    public com.fepoc.ac.acn.cmd.CommandHeader.LoginOrBuilder getLoginOrBuilder() {
      if ((authorizeCase_ == 1) && (loginBuilder_ != null)) {
        return loginBuilder_.getMessageOrBuilder();
      } else {
        if (authorizeCase_ == 1) {
          return (com.fepoc.ac.acn.cmd.CommandHeader.Login) authorize_;
        }
        return com.fepoc.ac.acn.cmd.CommandHeader.Login.getDefaultInstance();
      }
    }
    /**
     * <code>.command.CommandHeader.Login login = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.fepoc.ac.acn.cmd.CommandHeader.Login, com.fepoc.ac.acn.cmd.CommandHeader.Login.Builder, com.fepoc.ac.acn.cmd.CommandHeader.LoginOrBuilder> 
        getLoginFieldBuilder() {
      if (loginBuilder_ == null) {
        if (!(authorizeCase_ == 1)) {
          authorize_ = com.fepoc.ac.acn.cmd.CommandHeader.Login.getDefaultInstance();
        }
        loginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.fepoc.ac.acn.cmd.CommandHeader.Login, com.fepoc.ac.acn.cmd.CommandHeader.Login.Builder, com.fepoc.ac.acn.cmd.CommandHeader.LoginOrBuilder>(
                (com.fepoc.ac.acn.cmd.CommandHeader.Login) authorize_,
                getParentForChildren(),
                isClean());
        authorize_ = null;
      }
      authorizeCase_ = 1;
      onChanged();;
      return loginBuilder_;
    }

    /**
     * <code>bytes accessToken = 2;</code>
     * @return The accessToken.
     */
    public com.google.protobuf.ByteString getAccessToken() {
      if (authorizeCase_ == 2) {
        return (com.google.protobuf.ByteString) authorize_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes accessToken = 2;</code>
     * @param value The accessToken to set.
     * @return This builder for chaining.
     */
    public Builder setAccessToken(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  authorizeCase_ = 2;
      authorize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes accessToken = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccessToken() {
      if (authorizeCase_ == 2) {
        authorizeCase_ = 0;
        authorize_ = null;
        onChanged();
      }
      return this;
    }

    private java.lang.Object application_ = "";
    /**
     * <code>string application = 3;</code>
     * @return The application.
     */
    public java.lang.String getApplication() {
      java.lang.Object ref = application_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        application_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string application = 3;</code>
     * @return The bytes for application.
     */
    public com.google.protobuf.ByteString
        getApplicationBytes() {
      java.lang.Object ref = application_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        application_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string application = 3;</code>
     * @param value The application to set.
     * @return This builder for chaining.
     */
    public Builder setApplication(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      application_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string application = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearApplication() {
      
      application_ = getDefaultInstance().getApplication();
      onChanged();
      return this;
    }
    /**
     * <code>string application = 3;</code>
     * @param value The bytes for application to set.
     * @return This builder for chaining.
     */
    public Builder setApplicationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      application_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:command.CommandHeader)
  }

  // @@protoc_insertion_point(class_scope:command.CommandHeader)
  private static final com.fepoc.ac.acn.cmd.CommandHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fepoc.ac.acn.cmd.CommandHeader();
  }

  public static com.fepoc.ac.acn.cmd.CommandHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommandHeader>
      PARSER = new com.google.protobuf.AbstractParser<CommandHeader>() {
    @java.lang.Override
    public CommandHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommandHeader(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommandHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommandHeader> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fepoc.ac.acn.cmd.CommandHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

